spring:
    profiles:
        active: dev

---
server:
  port: 8001

mybatis:
  type-aliases-package: com.konbai.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml

spring:
  profiles: dev
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://gocit.top:3306/db1?useUnicode=true&characterEncoding=utf-8
    username: root
    password: lcjdmm

#配置eureka服务器的地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: springcloud-provider-dept8001

#给该服务添加一些信息
info:
  app.name: konbai
---
spring:
  profiles: test
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://gocit.top:3306/db2?useUnicode=true&characterEncoding=utf-8
    username: root
    password: lcjdmm

#配置eureka服务器的地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: springcloud-provider-dept8001

#给该服务添加一些信息
info:
  app.name: konbai

